### ISSUE TITLE
Make a pypi package

### ISSUE THREAD

**Issue by akotlar** [SomaLogic/Canopy#6]
Could you please make a pypi package? Having Canopy as a dependency is difficult if you wish to publish your project to pypi, because pyproject.toml dependencies cannot be GitHub sourced:

```
 <h1>400 Can't have direct dependency: canopy@ git+https://github.com/bystrogenomics/canopy.git@f6d3031494a692db040492fa1dead5faf19fef5a. See https://packaging.python.org/specifications/core-metadata for more information.</h1>
```

**Comment by tjohnson-somalogic** [comment]
Hi @akotlar Thank you for your interest in using canopy. Making a PyPI package has been on my mind lately but has been back burner-ed because I wasn't sure there was demand.  I will bring it forward now.  Unfortunately the `canopy` namespace is occupied in pypi, we will work through that and update you here.

**Comment by akotlar** [comment]
> Hi @akotlar Thank you for your interest in using canopy. Making a PyPI package has been on my mind lately but has been back burner-ed because I wasn't sure there was demand.  I will bring it forward now.  Unfortunately the `canopy` namespace is occupied in pypi, we will work through that and update you here. 

Awesome thanks. It would mostly simplify things for your users that want to include canopy as a dependency. The namespace could be somalogic-canopy say.

**Comment by akotlar** [comment]
Works great, thanks
